config/routes.rb
Static::Application.routes.draw do
  get "microposts/create"

  get "microposts/destroy"

  resources :users
  resources :sessions,:only =>[:new,:create,:destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root :to => "pages#index"

  match '/new', :to => 'users#new'

  match '/edit', :to => 'users#edit'

  match '/sessions', :to => 'sessions#create'

  match '/signin',:to => 'sessions#new'

  match '/signout',:to => 'sessions#destroy'

  get '/contact', :to => 'pages#contact'

  get "/propos", :to => 'pages#propos'

  get "/help", :to => 'pages#help'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    collection do
      get :tigers
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom" >
  <span>&copy; <%= creator %></span>
</footer>

app/views/layouts/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-costum navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag "site.png",:width=>"40",:height=>"40",:class=>"logo" %>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href=" <%= root_path %>" style="font-weight:bold">
            Home
            <% if signed_in? %>
            <span class="badge"><%= current_user.microposts.count %></span>
            <% end %>
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li><%= link_to "Contact",contact_path,:style=>"font-weight:bold" %></li>
        <li><%= link_to "About",propos_path,:style=>"font-weight:bold" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !signed_in? %>
        <li>
          <%= link_to new_path,:style=>"font-weight:bold" do %>
          Sign up
          <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </li>
        <li>
          <%= link_to new_session_path,:style=>"font-weight:bold" do %>
          Sign in
          <span class="glyphicon glyphicon-user"></span>
          <% end %>
        </li>
        <% else %>
        <li>
          <%= link_to edit_user_path(current_user),:style=>"font-weight:bold" do %>
          Settings
          <span class="glyphicon glyphicon-cog"></span>
          <% end %>
        </li>
        <li>
          <%= link_to user_path(current_user),:style=>"font-weight:bold" do %>
          Profile
          <span class="glyphicon glyphicon-user"></span>
          <% end %>
        </li>
        <li>
          <%= link_to users_path,:style=>"font-weight:bold" do %>
          Users
          <span class="glyphicon glyphicon-blackboard"></span>
          <% end %>
        </li>
        <li>
          <%= link_to "#",:style=>"font-weight:bold" do %>
          Help
          <span class="glyphicon glyphicon-question-sign"></span>
          <% end %>
        </li>
        <li>
          <%= link_to signout_path,:id=>"signout",:style=>"font-weight:bold;color:white;text-decoration:none;",:method => :delete do %>
          Sign out
          <span class="glyphicon glyphicon-off"></span>
        </li>

        <% end %>

        <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The <%= @title.capitalize %> page</title>
  <%= csrf_meta_tag %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <!--[if lt IE 8]>
  <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection">
  <![endif]-->
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'css/bootstrap.min' %>
  <%= stylesheet_link_tag 'css/sticky-footer-navbar' %>
  <%= stylesheet_link_tag 'css/commun' %>
  <%= yield :head %>
</head>
<body>
  <div class="container">
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </div><!--container-->
  <%= javascript_include_tag "js/jquery-2.2.1.min" %>
  <%= javascript_include_tag "js/bootstrap.min" %>
  <%= javascript_include_tag :defaults %>
  <%= yield :script %>
</body>
</html>